# Generated by Django 5.1.5 on 2025-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(default='default@example.com', max_length=255),
        ),
    ]
