# Generated by Django 5.1.5 on 2025-02-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_rename_age_author_age_rename_name_author_name_and_more'),
        ('blog', '0002_category_blog_author_alter_blog_title_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='author.author'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
